services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    restart: unless-stopped


  info_bot:
    build:
      context: ./info_bot
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      server:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
